---
- hosts: ansible-target-1 
  remote_user: ec2-user
  tasks:
    - name: comand execution
      command: echo $HOSTNAME
      register: cmdout
    - debug: msg=" {{cmdout.stdout}} " 
    - name: shell execution
      shell: echo $HOSTNAME
      register: shout
    - debug: msg=" {{shout.stdout}} "

