---
- hosts: ansible-target-2
  remote_user: ec2-user
  tasks:
  - name: get inventory from inventory_hostnames
    debug:
     msg: "{{item}}"
    loop: "{{query('inventory_hostnames','ansible-target-2')}}"


